package top.jf.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.jf.entity.KeyWord;
import top.jf.entity.KeyWordExample;

public interface KeyWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    int countByExample(KeyWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    int deleteByExample(KeyWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    int insert(KeyWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    int insertSelective(KeyWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    List<KeyWord> selectByExample(KeyWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    KeyWord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") KeyWord record, @Param("example") KeyWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    int updateByExample(@Param("record") KeyWord record, @Param("example") KeyWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    int updateByPrimaryKeySelective(KeyWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    int updateByPrimaryKey(KeyWord record);
    
    List<String> findAllWords();
    
    Integer delSensitiveWord(String text);
}