spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
#    devtools热部署规范
  devtools:
    restart:
      enabled: false
#  thymeleaf:
#    cache: false
  mvc:
    view:
      prefix: /static/
      suffix: .jsp
# 自定义访问静态资源路径
    resources:
      static-locations: classpath:/static/



#运行使用aop
#  aop:
#    auto: true
# 访问jsp配置
# MyBatis
mybatis:
#    typeAliasesPackage: top.jf.entity
    mapperLocations: classpath:mybatis/sqlmap/*.xml
#    configLocation: classpath:/mybatis-config.xml


#mybatis-plus 配置
#mybatis-plus:
#    typeAliasesPackage: top.jf.entity
#    mapperLocations: classpath:mybatis/sqlmap/*.xml
#    global-config:
#     #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: 2
#      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: 2
#      #驼峰下划线转换
#      db-column-underline: true
#      #刷新mapper 调试神器
#      refresh-mapper: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      #序列接口实现类配置
#      #key-generator: com.baomidou.springboot.xxx
#      #逻辑删除配置
#      #logic-delete-value: 0
#      #logic-not-delete-value: 1
#      #自定义填充策略接口实现
#      #meta-object-handler: com.baomidou.springboot.xxx
#      #自定义SQL注入器
#      #sql-injector: com.baomidou.springboot.xxx
#    configuration:
#      map-underscore-to-camel-case: true
#      cache-enabled: false



# LOGGING
logging:
    level:
       com.alibaba.druid.pool.DruidDataSource: error
       top.jf.mapper: debug
# Spring Boot启动时将自动配置的信息通过DEBUG级别的日志打印到控制台
debug: false


