package top.jf.entity;

import java.util.Date;

public class KeyWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word.id
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word.key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    private String keyWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word.create_time
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word.id
     *
     * @return the value of key_word.id
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word.id
     *
     * @param id the value for key_word.id
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word.key_word
     *
     * @return the value of key_word.key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word.key_word
     *
     * @param keyWord the value for key_word.key_word
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word.create_time
     *
     * @return the value of key_word.create_time
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word.create_time
     *
     * @param createTime the value for key_word.create_time
     *
     * @mbggenerated Fri Nov 24 10:51:08 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    
}